## Utils

In [1]:
import warnings
warnings.filterwarnings("ignore")                     #Ignoring unnecessory warnings

import numpy as np                                  #for large and multi-dimensional arrays
import pandas as pd                                 #for data manipulation and analysis
import nltk                                         #Natural language processing tool-kit

from nltk.corpus import stopwords                   #Stopwords corpus
from nltk.stem import PorterStemmer                 # Stemmer

from sklearn.feature_extraction.text import CountVectorizer          #For Bag of words
from sklearn.feature_extraction.text import TfidfVectorizer          #For TF-IDF

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from gensim.models import Word2Vec                                   #For Word2Vec


## Loading Data Using Pandas:

In [3]:
pip install spicy

  Using cached spicy-0.16.0-py2.py3-none-any.whl.metadata (310 bytes)
  Using cached scipy-1.14.0-cp311-cp311-win_amd64.whl.metadata (60 kB)
Using cached spicy-0.16.0-py2.py3-none-any.whl (1.7 kB)
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.7 MB ? eta -:--:--
   ------------------------------

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\shiza\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\shiza\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiza\anaconda3\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiza\anaconda3\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiza\anaconda3\Lib\http\client.py", line 473, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\shiza\anaconda3\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^

In [2]:
import pandas as pd
pd.pandas.set_option('display.max_columns',None)
pd.pandas.set_option('display.max_rows',None)
df = pd.read_csv('resume_data2.csv')
df.head()

Unnamed: 0                                             cv_txt  score
0           0  Your Name November 13, 2019 Short description ...      7
1           1  Last Updated on 21st June 2019 Debarghya Das d...      6
2           2  DougHeffernan Passionate Driver EDUCATION Marc...      9
3           3  Jon Snow HOUSE Stark REALM Kingdom of The Nort...      9
4           4  Experience Sep/2015 Present Job 4 Employer, Co...      0

In [3]:
df.drop(['Unnamed: 0'],inplace=True,axis=1)

### Some Basic Exploratory Data Analysis:

In [4]:
df.head()

cv_txt  score
0  Your Name November 13, 2019 Short description ...      7
1  Last Updated on 21st June 2019 Debarghya Das d...      6
2  DougHeffernan Passionate Driver EDUCATION Marc...      9
3  Jon Snow HOUSE Stark REALM Kingdom of The Nort...      9
4  Experience Sep/2015 Present Job 4 Employer, Co...      0

In [5]:
df.shape

(319, 2)

In [6]:
df.isna().sum()

cv_txt    0
score     0
dtype: int64

### Data Preprocessing:

In [7]:
for i in range(1,3):
    print(df['cv_txt'].values[i])
    print('-----------------------------------------------------')

Last Updated on 21st June 2019 Debarghya Das debarghyadas.com| fb.co/dd deedy@fb.com | 607.379.5733 | dd367@cornell.edu EDUCATION CORNELL UNIVERSITY MENG IN COMPUTER SCIENCE Dec 2014 | Ithaca, NY CORNELL UNIVERSITY BS IN COMPUTER SCIENCE May 2014 | Ithaca, NY College of Engineering Magna Cum Laude Cum. GPA: 3.83 / 4.0 Major GPA: 3.9 / 4.0 LA MARTINIERE FOR BOYS Grad. May 2011| Kolkata, India LINKS Facebook:// dd Github:// deedydas LinkedIn:// debarghyadas YouTube:// DeedyDash007 Twitter:// @debarghya_das Quora:// Debarghya-Das COURSEWORK GRADUATE Advanced Machine Learning Open Source Software Engineering Advanced Interactive Graphics Compilers + Practicum Cloud Computing Evolutionary Computation Defending Computer Networks Machine Learning UNDERGRADUATE Information Retrieval Operating Systems Artificial Intelligence + Practicum Functional Programming Computer Graphics + Practicum (Research Asst. & Teaching Asst 2x) Unix Tools and Scripting SKILLS PROGRAMMING Over 5000 lines: Java • She

In [8]:
df.isna().sum()

cv_txt    0
score     0
dtype: int64

In [9]:
df_x = df['cv_txt']
df_y = df['score']

In [10]:
stop_words = set(stopwords.words('english'))
len(stop_words) #finding stop words

179

In [11]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
snow = nltk.stem.SnowballStemmer('english')

corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['cv_txt'][i])
    review = review.lower()
    review = review.split()
    
    review = [snow.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [17]:
corpus[1]

'last updat st june debarghya das debarghyada com fb co dd deedi fb com dd cornel edu educ cornel univers meng comput scienc dec ithaca ny cornel univers bs comput scienc may ithaca ny colleg engin magna cum laud cum gpa major gpa la martinier boy grad may kolkata india link facebook dd github deedyda linkedin debarghyada youtub deedydash twitter debarghya das quora debarghya das coursework graduat advanc machin learn open sourc softwar engin advanc interact graphic compil practicum cloud comput evolutionari comput defend comput network machin learn undergradu inform retriev oper system artifici intellig practicum function program comput graphic practicum research asst teach asst x unix tool script skill program line java shell python javascript ocaml matlab rail latex line c c css php assembl familiar io android mysql experi facebook softwar engin jan present new york ny coursera kpcb fellow softwar engin intern june sep mountain view ca applic chosen kpcb fellow led ship yoda admin i

In [18]:
df_x = corpus

In [19]:
type(df_x)

list

In [20]:
voc_size=5000
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
type(onehot_repr)

list

In [21]:
sent_length=400
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2004 1907  817]
 [   0    0    0 ... 2394 4602  662]
 [   0    0    0 ... 1873  424 4903]
 ...
 [   0    0    0 ...  160 3063  443]
 [4769  187 4675 ... 3063 3063  443]
 [   0    0    0 ... 3041 3063  443]]


In [40]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_shape=(sent_length,)))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_14 (Embedding)             │ (None, 400, 40)             │         200,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_12 (Dropout)                 │ (None, 400, 40)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_6 (LSTM)                        │ (None, 100)                 │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_13 (Dropout)                 │ (None, 100)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [41]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(df_y)

### Train Test Split:

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_final, y_final, test_size=0.2, random_state=42)

In [44]:
#we are feeding the 
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,batch_size=64)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 791ms/step - accuracy: 0.1205 - loss: -183.2738 - val_accuracy: 0.1094 - val_loss: -182.1538
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 742ms/step - accuracy: 0.0851 - loss: -192.7750 - val_accuracy: 0.1094 - val_loss: -183.5315
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 724ms/step - accuracy: 0.1179 - loss: -190.8933 - val_accuracy: 0.1094 - val_loss: -184.8983
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 733ms/step - accuracy: 0.0986 - loss: -193.8680 - val_accuracy: 0.1094 - val_loss: -186.2675
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 797ms/step - accuracy: 0.1002 - loss: -189.1744 - val_accuracy: 0.1094 - val_loss: -187.6324
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 806ms/step - accuracy: 0.0986 - loss: -190.5006 - val_accuracy: 0.1094 - val_loss: -189.0014
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 829ms/step - accuracy: 0.0903 - loss: -194.9639 - val_accuracy: 0.1094 - val_loss: -190.3685
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 826ms/step - accuracy: 0.0950

In [49]:
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)


2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 120ms/step


In [54]:

accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.109375


### TF-IDF:

In [55]:
final_tf = df_x
tf_idf = TfidfVectorizer(ngram_range=(1,2),max_features=5000)
tf_data = tf_idf.fit_transform(final_tf)
print(tf_data[1])

  (0, 1409)	0.010177758526163367
  (0, 4660)	0.02987500573725461
  (0, 1753)	0.028176741948372476
  (0, 332)	0.023187940668397387
  (0, 2402)	0.03600604568761869
  (0, 4680)	0.02560183148382079
  (0, 4125)	0.05987387102141208
  (0, 2294)	0.04052411402420102
  (0, 1044)	0.22767649267949572
  (0, 780)	0.019664872681763663
  (0, 1688)	0.0882496544639451
  (0, 749)	0.01266194070840155
  (0, 1096)	0.12258380596580172
  (0, 936)	0.34471699337154704
  (0, 1408)	0.038460648258251226
  (0, 846)	0.1039319431338827
  (0, 3759)	0.0381770720252551
  (0, 1118)	0.031773062719522314
  (0, 2223)	0.2462264238368193
  (0, 2946)	0.2509518738266065
  (0, 2676)	0.10327832007982579
  (0, 775)	0.013359417434252
  (0, 1482)	0.08648703679197389
  (0, 2553)	0.035483048950987035
  (0, 1000)	0.07997837019123628
  :	:
  (0, 2547)	0.06648038050661897
  (0, 2990)	0.06814515529412091
  (0, 4063)	0.04553529853589914
  (0, 4023)	0.10680458462718473
  (0, 741)	0.04086126865526724
  (0, 2997)	0.02305628441298117
  (0, 258

In [57]:
import pickle

pickle.dump(tf_idf, open("tfidf_vectorizer.pkl", "wb"))

In [58]:
v = pickle.load(open('tfidf_vectorizer.pkl','rb'))

In [59]:
tf_data.get_shape()

(319, 5000)

In [62]:
features = v.get_feature_names_out()  # Or v.get_feature_names() if using an older scikit-learn version
print(features[:10])

['aa' 'ab' 'abap' 'abap kolkata' 'abc' 'abil' 'abil quick' 'abil work'
 'abl' 'abroad']


In [63]:
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
df_y1 = encode.fit_transform(df_y)
type(df_y1)

numpy.ndarray

In [64]:
# pd.DataFrame(['df_y1'])

In [65]:
SEED =42
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val = train_test_split(tf_data,df_y,test_size = 0.2,random_state=SEED)

In [66]:
from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB().fit(x_train, y_train)

y_pred_nb=nb_model.predict(x_val)

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_pred_nb)

0.09375

### Random Forest:

In [68]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf_model = rf.fit(x_train,y_train)
y_pred_rf = rf_model.predict(x_val)
accuracy_score(y_val,y_pred_rf)

0.125

In [69]:
import pickle
pickle.dump(rf_model,open('rf_score_model.pkl','wb'))

In [70]:
#TESTING WITH SOME DATE
test = 'last updat st june debarghya das debarghyada com fb co dd deedi fb com dd cornel edu educ cornel univers meng comput scienc dec ithaca ny cornel univers bs comput scienc may ithaca ny colleg engin magna cum laud cum gpa major gpa la martinier boy grad may kolkata india link facebook dd github deedyda linkedin debarghyada youtub deedydash twitter debarghya das quora debarghya das coursework graduat advanc machin learn open sourc softwar engin advanc interact graphic compil practicum cloud comput evolutionari comput defend comput network machin learn undergradu inform retriev oper system artifici intellig practicum function program comput graphic practicum research asst teach asst x unix tool script skill program line java shell python javascript ocaml matlab rail latex line c c css php assembl familiar io android mysql experi facebook softwar engin jan present new york ny coursera kpcb fellow softwar engin intern june sep mountain view ca applic chosen kpcb fellow led ship yoda admin interfac new phoenix platform full stack develop wrote review code js use backbon jade stylus requir scala use play googl softwar engin intern may aug mountain view ca work youtub caption team javascript python plan design develop full stack add edit automat speech recognit caption product creat backbon js like framework caption editor phabric open sourc contributor team leader jan may palo alto ca ithaca ny phabric use daili facebook dropbox quora asana creat meme generat php shell led team mit cornel ic london uhelsinki project research cornel robot learn lab research jan jan ithaca ny work ashesh jain prof ashutosh saxena creat planit tool learn larg scale user prefer feedback plan robot trajectori human environ cornel phonet lab head undergradu research mar may ithaca ny led develop quicktongu first ever breakthrough tongu control game prof sam tilsen aid linguist research award top kpcb engin fellow st microsoft code competit cornel nation jump trade challeng finalist th cs cach race bot tournament nd cs biannual intra class bot tournament nation indian nation mathemat olympiad inmo finalist public jain das saxena planit crowdsourc approach learn plan path larg scale prefer feedback tech report icra press tilsen das b mckee real time articulatori biofeedback electromagnet articulographi linguist vanguard press'
snow = nltk.stem.SnowballStemmer('english')

corpus_test = []
# for i in range(0, len(df)):
review = re.sub('[^a-zA-Z]', ' ', test)
review = review.lower()
review = review.split()
    
review = [snow.stem(word) for word in review if not word in stopwords.words('english')]
review = ' '.join(review)
corpus_test.append(review)

In [71]:
final_tf_test = corpus_test
# tf_idf_test = TfidfVectorizer(ngram_range=(1,2),max_features=5000)
tf_data_test = v.transform(final_tf_test)
tf_data_test.get_shape()

(1, 5000)

In [72]:
loaded_model = pickle.load(open('rf_score_model.pkl', 'rb'))
result = loaded_model.predict(tf_data_test)
print(result)

[6]


### rf with rscv:

In [73]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]



random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

cls_rf_rscv = RandomForestClassifier()
from sklearn.model_selection import RandomizedSearchCV

random_search_rf = RandomizedSearchCV(cls_rf_rscv, random_grid,n_iter=5, n_jobs=1, cv=5,verbose=2)
random_search_rf.fit(x_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END bootstrap=False, max_depth=90, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=1800; total time=  14.4s
[CV] END bootstrap=False, max_depth=90, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=1800; total time=  14.7s
[CV] END bootstrap=False, max_depth=90, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=1800; total time=  14.1s
[CV] END bootstrap=False, max_depth=90, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=1800; total time=  15.4s
[CV] END bootstrap=False, max_depth=90, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=1800; total time=  15.2s
[CV] END bootstrap=True, max_depth=50, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=600; total time=   0.0s
[CV] END bootstrap=True, max_depth=50, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estima

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=5, n_jobs=1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   verbose=2)

In [74]:
random_search_rf.best_params_

{'n_estimators': 1800,
 'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 90,
 'bootstrap': False}

In [75]:
base_model = RandomForestClassifier(n_estimators= 2000,
                                     min_samples_split= 10,
                                     min_samples_leaf= 1,
                                     max_features= 'sqrt',
                                     max_depth= 90,
                                     bootstrap= True,
                                    random_state = SEED)
base_model.fit(x_train, y_train)

RandomForestClassifier(max_depth=90, min_samples_split=10, n_estimators=2000,
                       random_state=42)

In [78]:
y_pred_rf_rscv = base_model.predict(x_val)

In [79]:
# y_pred_rf_rscv = rf_rscv_model.predict(x_val)
accuracy_score(y_val,y_pred_rf_rscv)

0.078125